# fly.toml app configuration file for arbitrage-app1
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arbitrage-app1"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"

[deploy]
  working_dir = "/app/backend"

[processes]
  app = "node bot.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
